modLoader="javafml"
loaderVersion="[42,)"
credits="vincentmet"
license="All Rights Reserved"
[[mods]]
modId="mkm"
version="1.19.1-2.2.0"
displayName="Macro Keybind Mod"
description='''
Macro!!!Macro!!!Macro!!!
'''