modLoader="javafml"
loaderVersion="[47,)"
credits="vincentmet"
license="All Rights Reserved"
[[mods]]
modId="mkm"
version="1.20.1-2.3.0"
displayName="Macro Keybind Mod"
description='''
Macro!!!Macro!!!Macro!!!
'''