modLoader="javafml"
loaderVersion="[44,)"
credits="vincentmet"
license="All Rights Reserved"
[[mods]]
modId="mkm"
version="1.19.3-2.3.0"
displayName="Macro Keybind Mod"
description='''
Macro!!!Macro!!!Macro!!!
'''