modLoader="javafml"
loaderVersion="[40,)"
credits="vincentmet"
license="All Rights Reserved"
[[mods]]
modId="mkm"
version="1.18.2-2.0.0"
displayName="Macro"
description='''
Macro!!!Macro!!!Macro!!!
'''